# 1. Use an official Python base image
FROM python:3.11-slim

# 2. Set working directory inside the container
WORKDIR /app

# 3. Copy requirements.txt first to leverage Docker layer caching
COPY requirements.txt .

# 4. Install dependencies
RUN apt-get update && apt-get install -y vim-tiny curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y iputils-ping iproute2
RUN pip install --upgrade pip

# 5. Copy the rest of your app files into the container
# (adjust the pattern if you have subfolders or static files)
COPY my_mlflow_web.py /app

# 6. Expose the port that Uvicorn will run on
EXPOSE 8045

# Environment variable
ENV FASTAPI_MLFLOW=http://fastapi-mlflow:8030
ENV FASTAPI_DOCKER=http://fastapi-docker:8020

# 7. Run the FastAPI app with Uvicorn
CMD ["./my_mlflow_web.py"]

