# 1. Use an official Python base image
FROM postgres:15

# 2. Set working directory inside the container
WORKDIR /app

# 3. Copy requirements.txt first to leverage Docker layer caching

# 4. Install dependencies
RUN apt-get update && apt-get install -y vim-tiny curl && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y iputils-ping iproute2

# 5. Copy the rest of your app files into the container
# (adjust the pattern if you have subfolders or static files)

# 6. Expose the port that Uvicorn will run on
EXPOSE 5432

# 7. Run the FastAPI app with Uvicorn

