# 1. Use an official Python base image
FROM python:3.11-slim

# 2. Set working directory inside the container
WORKDIR /app

# 3. Copy requirements.txt first to leverage Docker layer caching
COPY requirements.txt .

# 4. Install dependencies
RUN apt-get update && apt-get install -y vim-tiny curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y iputils-ping iproute2
RUN pip install --upgrade pip

# Deep Clean: Remove All Docker SDK Traces
RUN pip uninstall docker docker-py docker-pycreds requests urllib3 -y
RUN pip install docker==6.1.3 requests==2.31.0 urllib3==1.26.18
RUN pip list | grep docker


# 5. Copy the rest of your app files into the container
# (adjust the pattern if you have subfolders or static files)
COPY my_mlflow.py /app
COPY my_mlflow_fast_api.py /app
COPY my_mlflow_web.py /app

# 6. Expose the port that Uvicorn will run on
EXPOSE 8020

ENV MLFLOW_TRACKING_URI=http://mlflow-server:5000
ENV DOCKER_HOST=unix:///var/run/docker.sock

# 7. Run the FastAPI app with Uvicorn
# Replace 'main:app' with your actual module and FastAPI instance name
CMD ["uvicorn", "my_mlflow_fast_api:app", "--host", "0.0.0.0", "--port", "8020"]

