# 1. Use an official Python base image
FROM python:3.11-slim

# 2. Set working directory inside the container
WORKDIR /app

# 3. Copy requirements.txt first to leverage Docker layer caching
COPY requirements.txt .

# 4. Install dependencies
RUN apt-get update && apt-get install -y vim-tiny curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y iputils-ping iproute2
RUN pip install minio
RUN pip install --upgrade pip

# 5. Copy the rest of your app files into the container
# (adjust the pattern if you have subfolders or static files)
COPY my_mlflow.py /app
COPY my_mlflow_fast_api.py /app

# 6. Expose the port that Uvicorn will run on
EXPOSE 8030

ENV MLFLOW_TRACKING_URI=http://mlflow-server:5000
ENV DOCKER_HOST=unix:///var/run/docker.sock

# ENV MINIO_HTTP=minio
# ENV MINIO_HTTP=localhost
ENV MINIO_HTTP=minio-server
ENV MINIO_ROOT_USER=minioadmin
ENV MINIO_ROOT_PASSWORD=minioadmin

# 7. Run the FastAPI app with Uvicorn
# Replace 'main:app' with your actual module and FastAPI instance name
CMD ["uvicorn", "my_mlflow_fast_api:app", "--host", "0.0.0.0", "--port", "8030"]

